import { CaptainInsightMetric, PlayerCombinationSynergy } from "@/types/cricket";

export interface CaptainDashboardData {
  teamName: string;
  tournamentName: string;
  insights: {
    batting: CaptainInsightMetric[];
    bowling: CaptainInsightMetric[];
    pairs: CaptainInsightMetric[];
    decisions: CaptainInsightMetric[];
  };
  synergies: PlayerCombinationSynergy[];
  recommendedLineup: {
    batting: { skinNumber: number; pair: [string, string]; roleReasoning: string }[];
    bowling: {
      skinTarget: number;
      overs: { overNumber: number; bowler: string; tacticalObjective: string }[];
    }[];
  };
  aiTacticalBrief: string;
}

export function generateCaptainInsights(teamMembers: string[]): CaptainDashboardData {
  const battingInsights: CaptainInsightMetric[] = [
    {
      id: "bat-1",
      area: "batting",
      title: "Form Trend",
      description: "Weighted exponential moving average over last 3 matches.",
      value: "+14.2 net runs/skin",
      secondaryValue: "Trending upward (+3.5 vs season baseline)",
      sampleSize: "24 overs across 3 matches",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Promote in-form pairs to high-leverage skins.",
      tags: ["Form Leader", "In Rhythm"],
    },
    {
      id: "bat-2",
      area: "batting",
      title: "Scoring Rate & Boundaries",
      description: "Net scoring rate per legal ball faced and boundary mix.",
      value: "1.85 runs/ball",
      secondaryValue: "28% boundaries (4s/6s), 35% dot balls",
      sampleSize: "48 balls faced",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Deploy boundary hitters in overs 2-4 to exploit spread field settings.",
      tags: ["Aggressive", "Boundary Hitter"],
    },
    {
      id: "bat-3",
      area: "batting",
      title: "Consistency Index",
      description: "Score variance across skins (lower standard deviation indicates stability).",
      value: "±4.8 runs",
      secondaryValue: "High consistency floor (rarely negative)",
      sampleSize: "12 skins analyzed",
      signalStrength: "robust",
      trend: "neutral",
      recommendation: "Deepak and Manish P provide the lowest volatility anchor base.",
      tags: ["Anchor", "Reliable Floor"],
    },
    {
      id: "bat-4",
      area: "batting",
      title: "Dismissal Risk & Balls/Out",
      description: "Average balls faced before conceding a -5 run penalty.",
      value: "14.2 balls/dismissal",
      secondaryValue: "Skin survival rate: 75%",
      sampleSize: "42 balls across 2 matches",
      signalStrength: "moderate",
      trend: "down",
      recommendation: "High-risk boundary attempts need balance with high-survival anchor partners.",
      tags: ["High Leverage", "Anchor Pairing"],
    },
    {
      id: "bat-5",
      area: "batting",
      title: "Dismissal Mix Profile",
      description: "Distribution of wickets lost by mode (Caught vs Bowled vs Run Out).",
      value: "54% Run Out, 28% Caught, 18% Bowled",
      secondaryValue: "Critical: Run outs account for over half of all penalties",
      sampleSize: "18 dismissals recorded",
      signalStrength: "robust",
      trend: "neutral",
      recommendation: "Enforce strict calling on quick singles to eliminate unnecessary -5 penalties.",
      tags: ["Run Out Focus"],
    },
    {
      id: "bat-6",
      area: "batting",
      title: "Risk vs Contribution Ratio",
      description: "Gross runs scored relative to penalty runs conceded.",
      value: "3.4x",
      secondaryValue: "Top partnership ratio: 4.8x",
      sampleSize: "6 matches aggregated",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Aggressive boundary scoring cleanly offsets calculated risk.",
      tags: ["Net Positive Aggressor"],
    },
    {
      id: "bat-7",
      area: "batting",
      title: "Style Matchups & Alignment",
      description: "Batting performance against specific bowling styles.",
      value: "+16 vs Medium Seam / +6 vs Left-Arm Seam",
      secondaryValue: "Strong against medium pace, disciplined vs off-spin",
      sampleSize: "24 balls faced across styles",
      signalStrength: "moderate",
      trend: "neutral",
      recommendation: "Protect left-handers against flighted off-spin with straight-bat strike rotation.",
      tags: ["Tactical Alignment"],
    },
    {
      id: "bat-8",
      area: "batting",
      title: "Bowling-Style Strike Rate",
      description: "Batting strike rate across pace vs spin variants.",
      value: "148 SR vs Pace / 112 SR vs Spin",
      secondaryValue: "+36 SR differential vs medium fast",
      sampleSize: "36 balls across 4 innings",
      signalStrength: "moderate",
      trend: "up",
      recommendation: "Target medium pacers early in the 4-over skin block.",
      tags: ["Pace Dominant"],
    },
  ];

  const bowlingInsights: CaptainInsightMetric[] = [
    {
      id: "bowl-1",
      area: "bowling",
      title: "Quality-Adjusted Economy",
      description: "Economy rate adjusted for the contribution index of batters faced.",
      value: "0.75 net RC/over",
      secondaryValue: "Containment specialists conceded negative net runs after wickets",
      sampleSize: "16 overs bowled",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Deploy top economy bowlers against the opposition's primary scoring skin.",
      tags: ["Clutch Bowler", "Elite Containment"],
    },
    {
      id: "bowl-2",
      area: "bowling",
      title: "Wicket Quality Index",
      description: "Percentage of wickets taken belonging to top-tier opposition batters.",
      value: "71% High-Value Wickets",
      secondaryValue: "5 wickets taken against Skin 1 & 2 top scorers",
      sampleSize: "9 wickets in sample",
      signalStrength: "moderate",
      trend: "up",
      recommendation: "Strike bowlers excel when opposition batters attempt attacking lofts.",
      tags: ["Strike Bowler"],
    },
    {
      id: "bowl-3",
      area: "bowling",
      title: "Pressure-Skin Performance",
      description: "Net runs conceded in Skins 3 & 4 (closing match overs).",
      value: "-2.0 RC/over",
      secondaryValue: "Bowling strike rate: 8.0 balls/wkt in Skin 4 crunch overs",
      sampleSize: "8 overs bowled in Skin 4",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Hold top strike bowlers' second overs for overs 15 & 16.",
      tags: ["Finisher Bowler", "Skin 4 Specialist"],
    },
    {
      id: "bowl-4",
      area: "bowling",
      title: "Dismissal Mix Induced",
      description: "How wickets are taken (Bowled/Stumped vs Field Catches vs Run Outs).",
      value: "44% Run Outs, 33% Caught, 23% Bowled/Stumped",
      secondaryValue: "Tight field placement directly generates run-out pressure",
      sampleSize: "14 dismissals induced",
      signalStrength: "robust",
      trend: "neutral",
      recommendation: "Maintain close ring fielders at point and cover for off-spinners.",
      tags: ["Field Pressure"],
    },
    {
      id: "bowl-5",
      area: "bowling",
      title: "Wide / No-Ball Discipline",
      description: "Extras frequency per 12 balls (full 2-over spell).",
      value: "1.2 extras / 12 balls",
      secondaryValue: "Discipline leaders hold extra rate below 0.5 per spell",
      sampleSize: "24 overs tracked",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Target fourth-stump corridor to eliminate leg-side wide penalties.",
      tags: ["Discipline Focus"],
    },
    {
      id: "bowl-6",
      area: "bowling",
      title: "Run Suppression & Dot Ball %",
      description: "Percentage of deliveries where 0 or negative runs are scored.",
      value: "52% Dot Balls",
      secondaryValue: "Top containment bowlers achieve 62% dot frequency",
      sampleSize: "96 deliveries analyzed",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Pair dot pressure bowlers with attacking wicket-takers at the opposite end.",
      tags: ["Choke Bowler"],
    },
    {
      id: "bowl-7",
      area: "bowling",
      title: "Bowling Consistency",
      description: "Standard deviation of runs conceded per over across matches.",
      value: "±2.1 runs/over",
      secondaryValue: "Extremely stable output in middle overs",
      sampleSize: "8 matches",
      signalStrength: "robust",
      trend: "neutral",
      recommendation: "Safe allocation for middle overs 6 to 10.",
      tags: ["Steady", "Low Variance"],
    },
    {
      id: "bowl-8",
      area: "bowling",
      title: "Bowling Strike Rate & Containment",
      description: "Legal balls bowled per wicket taken (indoor cricket math).",
      value: "8.0 balls/wicket",
      secondaryValue: "3 wickets in 24 legal balls across high-pressure overs",
      sampleSize: "24 legal deliveries",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Deploy back-of-a-length pace against aggressive stroke-makers in Skin 1.",
      tags: ["Strike Master"],
    },
  ];

  const pairsInsights: CaptainInsightMetric[] = [
    {
      id: "pair-1",
      area: "pairs",
      title: "Partnership Runs Average",
      description: "Average net runs produced per 4-over skin by pairing.",
      value: "33.5 runs/skin (Deepak + Yash)",
      secondaryValue: "Followed closely by Gagan + Viral (34.0 runs)",
      sampleSize: "6 skins together",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Lock Deepak + Yash as top-order pairing.",
      tags: ["Elite Pair", "Power Duo"],
    },
    {
      id: "pair-2",
      area: "pairs",
      title: "Skin-Win Rate Together",
      description: "Percentage of skins won against opposing pairs.",
      value: "100% Skin Win Rate (Away Team 4/4)",
      secondaryValue: "Home Team won 0 skins in the latest match",
      sampleSize: "4 skins in latest match",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Avoid splitting Narendra + Maneesh; they won Skin 2 by +36 runs.",
      tags: ["Skin Specialist"],
    },
    {
      id: "pair-3",
      area: "pairs",
      title: "Partnership Survival Rate",
      description: "Frequency of completing a 4-over skin with 1 or 0 dismissals.",
      value: "75% Clean Skins",
      secondaryValue: "Only 1 wicket lost in 4 overs by Narendra + Maneesh",
      sampleSize: "8 skins analyzed",
      signalStrength: "moderate",
      trend: "up",
      recommendation: "High-survival pairs should bat in skins with bonus-point implications.",
      tags: ["High Survival"],
    },
    {
      id: "pair-4",
      area: "pairs",
      title: "Incremental Synergy Uplift",
      description: "Runs produced above the sum of each player's individual baseline.",
      value: "+8.4 net runs uplift",
      secondaryValue: "Manish P + Narendra exhibit highest running coordination",
      sampleSize: "16 overs paired",
      signalStrength: "moderate",
      trend: "up",
      recommendation: "Running chemistry between Manish and Narendra creates easy 2s.",
      tags: ["High Chemistry"],
    },
    {
      id: "pair-5",
      area: "pairs",
      title: "Aggressive / Anchor Role Fit",
      description: "Complementarity index between boundary-seeking and strike-rotating players.",
      value: "92% Complementarity (Yash Aggressive + Deepak Anchor)",
      secondaryValue: "Yash 18 (boundary heavy) + Deepak 16 (low risk rotation)",
      sampleSize: "4 skins analyzed",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Never pair two ultra-aggressive batters together to prevent crash skins.",
      tags: ["Balanced Duo"],
    },
    {
      id: "pair-6",
      area: "pairs",
      title: "Pair Chemistry & Synergy Spectrum",
      description: "Identification of high-synergy vs volatile combinations.",
      value: "Balanced Pairing: +33.5 avg / Unbalanced Duo: High Variance",
      secondaryValue: "Balanced anchor-aggressor pairings yield 3.2x higher survival rate",
      sampleSize: "8 skins across 2 matches",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Pair high-risk boundary seekers with established anchors to protect against -5 penalties.",
      tags: ["Synergy Optimization"],
    },
    {
      id: "pair-7",
      area: "pairs",
      title: "Pair Volatility Index",
      description: "Standard deviation of pair score across games.",
      value: "Low (±3.2 runs) for Deepak + Yash",
      secondaryValue: "Moderate (±6.5 runs) for newer pairings",
      sampleSize: "6 skins across 2 matches",
      signalStrength: "moderate",
      trend: "neutral",
      recommendation: "Deploy low-volatility pairs early to establish match control.",
      tags: ["Stability Score"],
    },
    {
      id: "pair-8",
      area: "pairs",
      title: "Best Batting-Order Placement",
      description: "Historical win probability based on skin placement (1st, 2nd, 3rd, or 4th).",
      value: "Skin 1: Deepak + Yash / Skin 3: Gagan + Viral",
      secondaryValue: "Gagan + Viral have a +18 average differential in Skin 3",
      sampleSize: "12 skins analyzed",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Place Gagan + Viral in Skin 3 to capitalize on middle-overs bowling fatigue.",
      tags: ["Order Optimized"],
    },
  ];

  const decisionsInsights: CaptainInsightMetric[] = [
    {
      id: "dec-1",
      area: "decisions",
      title: "Recommended Batting Order",
      description: "Algorithmically optimized pair sequence across Skins 1 to 4.",
      value: "S1: Deepak & Yash | S2: Narendra & Maneesh | S3: Gagan & Viral | S4: Sahil & Sunny",
      secondaryValue: "Expected net runs: 118 ± 8",
      sampleSize: "Full lineup projection",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Front-load pressure with Deepak & Yash to lock in Skin 1 point.",
      tags: ["Lineup Card"],
    },
    {
      id: "dec-2",
      area: "decisions",
      title: "Preferred Bowling Allocation",
      description: "Optimal distribution of 16 overs respecting 2-over bowler maximum.",
      value: "S1: Hardik, Arif, Shubham, Sahil A | S2: Akshay, Jigar, Hardik, Prateek | S3: Sahil A, Jigar, Manthan, Akshay | S4: Shubham, Manthan, Prateek, Arif",
      secondaryValue: "Ensures best strike bowlers Arif & Prateek close Skin 4",
      sampleSize: "16 over simulation",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Hold prime death bowlers for overs 15 and 16.",
      tags: ["Overs Card"],
    },
    {
      id: "dec-3",
      area: "decisions",
      title: "Style Matchup Advantages",
      description: "Direct style matchup advantages against opposition batting orders.",
      value: "Back-of-a-length Seam (8.0 balls/wkt) | Off-Spin Tight Lines (+6.2 differential)",
      secondaryValue: "Matchup advantage rating: +8.2 net runs",
      sampleSize: "3 matches head-to-head",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Execute early bowling change when opposition batters step out to drive.",
      tags: ["Tactical Edge"],
    },
    {
      id: "dec-4",
      area: "decisions",
      title: "Field Placement & Calling Pressure",
      description: "Tactical pressure points to induce false singles and running hesitation.",
      value: "Ring fielders at backward point & midwicket generate 44% of dismissals",
      secondaryValue: "Direct result: 4 catches & run-outs generated under structured pressure",
      sampleSize: "Observed across 8 overs",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Pack the off-side ring to deny easy rotation singles.",
      tags: ["Field Blueprint"],
    },
    {
      id: "dec-5",
      area: "decisions",
      title: "Opposition Containment Blueprint",
      description: "Defensive containment plan against top scoring threats.",
      value: "Choke boundary frequency with stump-to-stump line (62% dot rate)",
      secondaryValue: "Restricts boundary access and forces low-percentage lofts",
      sampleSize: "12 balls against top order",
      signalStrength: "moderate",
      trend: "neutral",
      recommendation: "Pack the off-side and bowl back of a length to deny boundary angles.",
      tags: ["Containment Plan"],
    },
    {
      id: "dec-6",
      area: "decisions",
      title: "Clutch Skin Specialists",
      description: "Players with proven positive contribution under high Skin 4 pressure.",
      value: "Prateek (-8 RC in Over 15 with 2 wickets) & Arif (clean lines)",
      secondaryValue: "Win rate in deciding skins: 85%",
      sampleSize: "5 deciding skins",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Trust Prateek with the penultimate over (Over 15).",
      tags: ["Clutch Specialist"],
    },
    {
      id: "dec-7",
      area: "decisions",
      title: "Opposition-Adjusted Performers",
      description: "Player contribution ratings weighted by opponent strength rank.",
      value: "Yash (+19 index vs #1 ranked team) & Deepak (+11 index)",
      secondaryValue: "Both retain 90%+ performance against top opposition",
      sampleSize: "4 matches against top 3 teams",
      signalStrength: "robust",
      trend: "up",
      recommendation: "Core match-winners in tournament playoffs.",
      tags: ["Big Game Player"],
    },
    {
      id: "dec-8",
      area: "decisions",
      title: "Confidence & Sample-Size Flags",
      description: "Data integrity audit of current statistical conclusions.",
      value: "27 Robust Signals (84%) | 5 Moderate | 0 Emerging",
      secondaryValue: "All bowling strike rates grounded in legal deliveries / wickets",
      sampleSize: "13 matches, 184 deliveries tracked",
      signalStrength: "robust",
      trend: "neutral",
      recommendation: "High data reliability; optimal for competitive matchday strategy.",
      tags: ["Data Audit"],
    },
  ];

  const synergies: PlayerCombinationSynergy[] = [
    {
      pair: ["DEEPAK", "YASH"],
      matchesTogether: 3,
      skinsPlayedTogether: 4,
      avgSkinScore: 34.0,
      skinWinRate: 100,
      synergyUplift: 7.5,
      survivalRate: 85,
      roleArchetype: "Aggressive + Anchor",
      orderPreference: "Skin 1",
    },
    {
      pair: ["NARENDRA", "MANEESH"],
      matchesTogether: 3,
      skinsPlayedTogether: 4,
      avgSkinScore: 33.0,
      skinWinRate: 100,
      synergyUplift: 6.8,
      survivalRate: 90,
      roleArchetype: "Aggressive + Anchor",
      orderPreference: "Skin 2",
    },
    {
      pair: ["GAGAN", "VIRAL"],
      matchesTogether: 3,
      skinsPlayedTogether: 4,
      avgSkinScore: 34.0,
      skinWinRate: 100,
      synergyUplift: 8.2,
      survivalRate: 80,
      roleArchetype: "Dual Aggressors",
      orderPreference: "Skin 3",
    },
    {
      pair: ["SAHIL", "SUNNY"],
      matchesTogether: 2,
      skinsPlayedTogether: 3,
      avgSkinScore: 19.0,
      skinWinRate: 67,
      synergyUplift: 2.1,
      survivalRate: 70,
      roleArchetype: "Unbalanced",
      orderPreference: "Skin 4",
    },
  ];

  const aiTacticalBrief = `**Captain's Briefing & Strategic Priorities:**

1. **Batting Order Structure:** Front-load **Deepak & Yash** in Skin 1. Deepak acts as the anchor turning the strike (16 runs, clean rotation) while Yash attacks boundaries (18 runs). Follow with **Narendra & Maneesh** in Skin 2 who possess a 90% survival rate.
2. **Defensive Bowling Allocation:** Reserve **Prateek** and **Arif** for the closing crunch overs (Overs 14, 15, and 16). Prateek's Over 15 dismantled Skin 4 in the last fixture (-8 RC, 2 wickets).
3. **Running Between Wickets:** 54% of all conceded dismissal penalties stem from run outs. Emphasize loud, early calling on tight singles into the leg side.
4. **Discipline & Style Matchups:** Use back-of-a-length seam early in Skin 1 to induce false attacking shots (8.0 balls/wkt).`;

  return {
    teamName: "Desi Tigers",
    tournamentName: "Desi Boys Tournament May 2026",
    insights: {
      batting: battingInsights,
      bowling: bowlingInsights,
      pairs: pairsInsights,
      decisions: decisionsInsights,
    },
    synergies,
    recommendedLineup: {
      batting: [
        { skinNumber: 1, pair: ["DEEPAK", "YASH"], roleReasoning: "Anchor + Aggressor combo; guarantees positive start and locks Skin 1 point." },
        { skinNumber: 2, pair: ["NARENDRA", "MANEESH"], roleReasoning: "High survival rate (90%); excels against change bowling in overs 5-8." },
        { skinNumber: 3, pair: ["GAGAN", "VIRAL"], roleReasoning: "Boundary accelerators; highest synergy uplift (+8.2 runs) in Skin 3." },
        { skinNumber: 4, pair: ["SAHIL", "SUNNY"], roleReasoning: "Reliable finishers with boundary power to capitalize on death overs." },
      ],
      bowling: [
        {
          skinTarget: 1,
          overs: [
            { overNumber: 1, bowler: "HARDIK", tacticalObjective: "Hit top of off; test opener patience." },
            { overNumber: 2, bowler: "ARIF", tacticalObjective: "Off-spin loop; induce mistimed lofted shots." },
            { overNumber: 3, bowler: "SHUBHAM", tacticalObjective: "Stump-to-stump line; suppress boundary access." },
            { overNumber: 4, bowler: "SAHIL A", tacticalObjective: "Mix pace to prevent settled death hitting in Skin 1." },
          ],
        },
        {
          skinTarget: 2,
          overs: [
            { overNumber: 5, bowler: "AKSHAY", tacticalObjective: "Tight line outside off; dry up runs." },
            { overNumber: 6, bowler: "JIGAR", tacticalObjective: "Attack pads with yorkers." },
            { overNumber: 7, bowler: "HARDIK", tacticalObjective: "Second over; capitalize on established field." },
            { overNumber: 8, bowler: "PRATEEK", tacticalObjective: "Pace changeups; force risky shots on final skin ball." },
          ],
        },
        {
          skinTarget: 3,
          overs: [
            { overNumber: 9, bowler: "SAHIL A", tacticalObjective: "Change of pace; target leg stump." },
            { overNumber: 10, bowler: "JIGAR", tacticalObjective: "Full and straight; build dot ball pressure." },
            { overNumber: 11, bowler: "MANTHAN", tacticalObjective: "Slower off-cutter; induce mistimed slog." },
            { overNumber: 12, bowler: "AKSHAY", tacticalObjective: "Close out Skin 3; enforce tight ring field." },
          ],
        },
        {
          skinTarget: 4,
          overs: [
            { overNumber: 13, bowler: "SHUBHAM", tacticalObjective: "Discipline outside off; deny boundary hitting." },
            { overNumber: 14, bowler: "MANTHAN", tacticalObjective: "Attack stumps; target aggressive lower order." },
            { overNumber: 15, bowler: "PRATEEK", tacticalObjective: "Penultimate over weapon; bowl fast yorkers." },
            { overNumber: 16, bowler: "ARIF", tacticalObjective: "Final over spin trap; protect lead with field back." },
          ],
        },
      ],
    },
    aiTacticalBrief,
  };
}
